### ISSUE TITLE
generate.py RuntimeError: cublas runtime error : library not initialized at torch/lib/THC/THCGeneral.c

### ISSUE THREAD

**Issue by shirakad** [facebookresearch/fairseq-lua#131]
Hi All, 
Trying to run generate.py to test my new model I get the following error:

/mlconvgec2018/software/fairseq-py/pytorch/torch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [173,0,0], thread: [62,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
/mlconvgec2018/software/fairseq-py/pytorch/torch/lib/THC/THCTensorIndex.cu:321: void indexSelectLargeIndex(TensorInfo<T, IndexType>, TensorInfo<T, IndexType>, TensorInfo<long, IndexType>, int, int, IndexType, IndexType, long) [with T = float, IndexType = unsigned int, DstDim = 2, SrcDim = 2, IdxDim = -2]: block: [173,0,0], thread: [63,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File "/mlconvgec2018/software/fairseq-py/generate.py", line 167, in <module>
    main()
  File "/mlconvgec2018/software/fairseq-py/generate.py", line 108, in main
    translations = translator.generate(Variable(tokens.view(1, -1)), Variable(positions.view(1, -1)))
  File "/mlconvgec2018/software/fairseq-py/fairseq/sequence_generator.py", line 86, in generate
    return self._generate(src_tokens, src_positions, beam_size, maxlen)
  File "/mlconvgec2018/software/fairseq-py/fairseq/sequence_generator.py", line 99, in _generate
    encoder_out = model.encoder(src_tokens, src_positions)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 252, in __call__
    result = self.forward(*input, **kwargs)
  File "/mlconvgec2018/software/fairseq-py/fairseq/models/fconv.py", line 125, in forward
    x = self.fc1(x)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/module.py", line 252, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.5/site-packages/torch/nn/functional.py", line 575, in linear
    output = input.matmul(weight.t())
  File "/usr/local/lib/python3.5/site-packages/torch/autograd/variable.py", line 561, in matmul
    return torch.matmul(self, other)
  File "/usr/local/lib/python3.5/site-packages/torch/functional.py", line 191, in matmul
    output = torch.mm(tensor1, tensor2)
  File "/usr/local/lib/python3.5/site-packages/torch/autograd/variable.py", line 580, in mm
    return Addmm.apply(output, self, matrix, 0, 1, True)
  File "/usr/local/lib/python3.5/site-packages/torch/autograd/_functions/blas.py", line 26, in forward
    matrix1, matrix2, out=output)
RuntimeError: cublas runtime error : library not initialized at /mlconvgec2018/software/fairseq-py/pytorch/torch/lib/THC/THCGeneral.c:405

Did anyone encounter this kind of error?
Thanks, 
Shira

**Comment by jgehring** [comment]
This seems to concern the Python version of fairseq. Can you post the issue at https://github.com/pytorch/fairseq?

**Comment by shirakad** [comment]
I did @jgehring.
